#!/bin/bash

## example usage:
## bash pull

## no longer necessary because symbolic links are used
git pull
# rsync -arvuP --delete --exclude-from=exclude .emacs.d/ ~/.emacs.d/
# rsync -avuP .emacs ~/.emacs

## possibly recompile (bash commands)
## emacs --batch --eval '(byte-recompile-directory ".emacs.d/contents" 0)'
## rm -f .emacs.d/contents/contributed/folding.elc ## never compiles correctly
