#!/bin/bash

## example usage:
## bash pull

git pull
rsync -arvuP --delete --exclude-from=exclude .emacs.d/ ~/.emacs.d/
rsync -avuP .emacs ~/.emacs
## possibly recompile
## emacs --batch --eval '(byte-recompile-directory (expand-file-name "~/.emacs.d") 0)'
## rm -f ~/.emacs.d/contributed/folding.elc ## never compiles correctly
