#!/bin/bash

## example usage:
## bash pull

git pull
rsync -arvuP --delete .emacs.d/ ~/.emacs.d/
rsync -avuP .emacs ~/.emacs
emacs --batch --eval "(byte-recompile-directory (expand-file-name "~/.emacs.d") 0)"
